plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vf5regenlauncher'
    compileSdk 33

    defaultConfig {
        applicationId "com.vf5regenlauncher"
        minSdk 19
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            java.srcDirs += 'android'
            java.exclude '**/fyt/adapter/HotseatAdapter.java'
            java.exclude '**/fyt/car/**'
            java.exclude '**/fyt/skin/**'
            java.exclude '**/fyt/widget/**'
            java.exclude '**/com/syu/back/**'
            java.exclude '**/com/syu/car/**'
            java.exclude '**/com/syu/popwindow/**'
            java.exclude '**/com/syu/remote/**'
            java.exclude '**/com/syu/util/**'
            java.exclude '**/com/syu/utils/**'
            java.exclude '**/com/syu/weather/**'
            java.exclude '**/com/syu/widget/**'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
